name: highload-architect-monitoring

services:
  influxdb:
    image: influxdb:2.7.12
    ports:
      - 8086:8086
    networks:
      - monitoring
    env_file:
      - .env
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "$INFLUXDB_USERNAME"
      DOCKER_INFLUXDB_INIT_PASSWORD: "$INFLUXDB_PASSWORD"
      DOCKER_INFLUXDB_INIT_ORG: "$INFLUXDB_ORG"
      DOCKER_INFLUXDB_INIT_BUCKET: "$INFLUXDB_BUCKET"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "$INFLUXDB_TOKEN"
    volumes:
      - ./data/influxdb/data:/var/lib/influxdb2
      - ./data/influxdb/config:/etc/influxdb2

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes:
      - ./data/grafana:/var/lib/grafana

networks:
  monitoring: